"use client";

import { useState } from "react";
import { DocumentIcon, ArrowUpTrayIcon, PlusIcon, PaperAirplaneIcon, Bars3Icon, XMarkIcon, ClockIcon, CodeBracketIcon, CheckCircleIcon, EllipsisVerticalIcon, MagnifyingGlassIcon } from "@heroicons/react/24/outline";

const docs = [
  {name:"Django Guide.pdf", type:"PDF", size:"2.4 MB", status:"Ready"},
  {name:"FastAPI_Tutorial.docx", type:"DOCX", size:"1.8 MB", status:"Processing"},
  {name:"LangChain_Notes.txt", type:"TXT", size:"84 KB", status:"Ready"},
  {name:"ML_Basics.pdf", type:"PDF", size:"3.1 MB", status:"Ready"},
  {name:"System_Design.docx", type:"DOCX", size:"1.2 MB", status:"Ready"},
];
const history = ["How to create API in Django?","Explaining LangChain RAG","Python multithreading","Docker setup guide","What is vector database?","Explain Kubernetes","Machine Learning basics","React vs Next.js"];

function IconButton({children, className=""}:{children:React.ReactNode;className?:string}) { return <button className={`grid h-9 w-9 place-items-center rounded-lg text-slate-500 hover:bg-slate-100 ${className}`}>{children}</button> }

export default function Home() {
  const [mobileOpen,setMobileOpen]=useState(false);
  const [uploading,setUploading]=useState(false);
  const [message,setMessage]=useState("");
  const [messages,setMessages]=useState([{role:"user",text:"Can you give me an example of Django REST API with authentication?",time:"10:24 AM"},{role:"ai",text:"Sure! Here is a complete example of a Django REST API with authentication using Django REST Framework (DRF) and Token Authentication.",time:"10:24 AM"}]);
  const send=()=>{ if(!message.trim())return; const m=message.trim(); setMessages([...messages,{role:"user",text:m,time:"Now"},{role:"ai",text:"Based on your uploaded documents, I can answer this question and include code examples when requested. This response is a UI placeholder for your RAG API.",time:"Now"}]); setMessage(""); };
  return <div className="min-h-screen bg-[#f7f8fc]">
    <header className="hidden h-16 border-b border-slate-200 bg-white px-5 md:flex items-center justify-between">
      <div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-lg bg-indigo-600 text-white"><CodeBracketIcon className="h-5 w-5"/></div><span className="font-bold">RAG Chatbot</span></div>
      <button onClick={()=>setUploading(true)} className="flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white shadow-sm hover:bg-indigo-700"><PlusIcon className="h-4 w-4"/>Upload Document</button>
    </header>

    <div className="flex h-[calc(100vh-0px)] md:h-[calc(100vh-4rem)]">
      <aside className={`${mobileOpen?'translate-x-0':'-translate-x-full'} fixed inset-y-0 left-0 z-40 w-[290px] border-r border-slate-200 bg-[#111827] text-white transition-transform md:static md:translate-x-0`}>
        <div className="flex h-16 items-center justify-between px-5"><div className="flex items-center gap-3"><div className="grid h-8 w-8 place-items-center rounded-lg bg-indigo-500"><CodeBracketIcon className="h-5 w-5"/></div><b>RAG Chatbot</b></div><IconButton className="text-slate-300 hover:bg-slate-800" ><Bars3Icon className="h-5 w-5"/></IconButton></div>
        <div className="px-4"><button onClick={()=>setUploading(true)} className="flex w-full items-center justify-center gap-2 rounded-lg bg-indigo-500 px-4 py-2.5 text-sm font-semibold shadow-lg hover:bg-indigo-600"><PlusIcon className="h-4 w-4"/>Upload Document</button><button className="mt-2 flex w-full items-center gap-3 rounded-lg border border-slate-700 px-4 py-2.5 text-sm text-slate-200 hover:bg-slate-800"><PlusIcon className="h-4 w-4"/>New Chat</button></div>
        <div className="mt-6 px-4"><div className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">Documents</div>{docs.map((d,i)=><button key={d.name} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2 text-left text-sm ${i===0?'bg-slate-800':'hover:bg-slate-800'}`}><DocumentIcon className="h-4 w-4 shrink-0 text-slate-300"/><span className="min-w-0 flex-1 truncate">{d.name}</span>{d.status==='Ready'?<span className="rounded-full bg-emerald-500/15 px-2 py-0.5 text-[10px] text-emerald-300">Ready</span>:<span className="rounded-full bg-amber-500/15 px-2 py-0.5 text-[10px] text-amber-300">Processing</span>}</button>)}</div>
        <div className="mt-5 border-t border-slate-800 px-4 pt-5"><div className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-500">Chat History</div>{history.map((h,i)=><button key={h} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2 text-left text-sm ${i===0?'bg-slate-800 text-white':'text-slate-300 hover:bg-slate-800'}`}><ClockIcon className="h-4 w-4 shrink-0"/><span className="truncate">{h}</span></button>)}</div>
        <div className="absolute bottom-0 left-0 right-0 border-t border-slate-800 p-4"><div className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-indigo-500 text-xs font-bold">SM</div><div className="min-w-0"><div className="text-sm font-semibold">Sakib Malik</div><div className="truncate text-xs text-slate-500">sakib@example.com</div></div></div></div>
      </aside>
      {mobileOpen&&<div onClick={()=>setMobileOpen(false)} className="fixed inset-0 z-30 bg-black/40 md:hidden"/>}

      <main className="flex min-w-0 flex-1 flex-col">
        <div className="flex h-16 items-center justify-between border-b border-slate-200 bg-white px-4 md:px-6"><div className="flex items-center gap-3"><button onClick={()=>setMobileOpen(true)} className="grid h-9 w-9 place-items-center rounded-lg hover:bg-slate-100 md:hidden"><Bars3Icon className="h-5 w-5"/></button><DocumentIcon className="h-5 w-5 text-slate-500"/><b className="truncate">Django Guide.pdf</b><span className="rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-medium text-emerald-700">Ready</span></div><div className="flex gap-2"><IconButton><MagnifyingGlassIcon className="h-5 w-5"/></IconButton><IconButton><EllipsisVerticalIcon className="h-5 w-5"/></IconButton></div></div>
        <div className="flex min-h-0 flex-1">
          <section className="flex min-w-0 flex-1 flex-col bg-white">
            <div className="chat-scroll flex-1 overflow-y-auto px-4 py-6 md:px-10 lg:px-14">{messages.map((m,i)=><div key={i} className={`mb-7 flex gap-3 ${m.role==='user'?'justify-end':''}`}><div className={`flex max-w-3xl gap-3 ${m.role==='user'?'flex-row-reverse':''}`}><div className={`grid h-8 w-8 shrink-0 place-items-center rounded-full text-xs font-bold ${m.role==='user'?'bg-indigo-100 text-indigo-700':'bg-indigo-600 text-white'}`}>{m.role==='user'?'SM':'AI'}</div><div><div className={`rounded-2xl px-4 py-3 text-[15px] leading-7 ${m.role==='user'?'bg-indigo-50 text-slate-800':'bg-slate-50 text-slate-700'}`}>{m.text}{m.role==='ai'&&<div className="mt-4 space-y-3"><h3 className="font-bold text-slate-900">1. Install Required Packages</h3><div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-200 px-3 py-2 text-xs text-slate-500"><span>bash</span><button className="rounded px-2 py-1 hover:bg-slate-100">Copy</button></div><pre className="code-scroll overflow-x-auto p-4 text-sm leading-6 text-slate-700"><code>pip install django djangorestframework</code></pre></div><h3 className="font-bold text-slate-900">2. Project Structure</h3><div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="flex items-center justify-between border-b border-slate-200 px-3 py-2 text-xs text-slate-500"><span>text</span><button className="rounded px-2 py-1 hover:bg-slate-100">Copy</button></div><pre className="code-scroll overflow-x-auto p-4 text-sm leading-6 text-slate-700"><code>{`myproject/\n├── manage.py\n├── myproject/\n│   └── settings.py\n└── api/\n    ├── models.py\n    ├── views.py\n    ├── urls.py\n    └── serializers.py`}</code></pre></div></div>}</div><div className="mt-1 text-xs text-slate-400">{m.time}</div></div></div></div>)}</div>
            <div className="border-t border-slate-200 bg-white p-3 md:p-5"><div className="mx-auto flex max-w-4xl items-end gap-2 rounded-2xl border border-slate-300 bg-white p-2 shadow-sm focus-within:border-indigo-400 focus-within:ring-2 focus-within:ring-indigo-100"><button className="grid h-10 w-10 shrink-0 place-items-center rounded-xl text-slate-400 hover:bg-slate-100"><ArrowUpTrayIcon className="h-5 w-5"/></button><textarea value={message} onChange={e=>setMessage(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Ask a question about your document..." rows={1} className="max-h-32 min-h-10 flex-1 resize-none border-0 bg-transparent px-2 py-2 text-sm outline-none"/><button onClick={send} className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-indigo-600 text-white hover:bg-indigo-700"><PaperAirplaneIcon className="h-5 w-5"/></button></div><p className="mt-2 text-center text-[11px] text-slate-400">This assistant uses your uploaded documents to provide grounded answers.</p></div>
          </section>
          <aside className="hidden w-[310px] border-l border-slate-200 bg-slate-50 p-5 xl:block"><div className="text-sm font-bold">Current Document</div><div className="mt-3 rounded-xl border border-slate-200 bg-white p-4"><div className="flex gap-3"><div className="grid h-10 w-10 place-items-center rounded-lg bg-indigo-50 text-indigo-600"><DocumentIcon className="h-5 w-5"/></div><div className="min-w-0"><div className="truncate text-sm font-semibold">Django Guide.pdf</div><div className="text-xs text-slate-500">PDF · 2.4 MB</div></div></div><div className="mt-4 flex items-center gap-2 rounded-lg bg-emerald-50 px-3 py-2 text-xs text-emerald-700"><CheckCircleIcon className="h-4 w-4"/>Indexed and ready for chat</div><div className="mt-5 space-y-3 text-xs"><div className="flex justify-between"><span className="text-slate-500">File Type</span><b>application/pdf</b></div><div className="flex justify-between"><span className="text-slate-500">File Size</span><b>2.4 MB</b></div><div className="flex justify-between"><span className="text-slate-500">Pages</span><b>124</b></div><div className="flex justify-between"><span className="text-slate-500">Chunks</span><b>256</b></div><div className="flex justify-between"><span className="text-slate-500">Embeddings</span><b>text-embedding-3-large</b></div></div></div></aside>
        </div>
      </main>
    </div>

    {uploading&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/50 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Upload Document</h2><button onClick={()=>setUploading(false)} className="grid h-8 w-8 place-items-center rounded-lg hover:bg-slate-100"><XMarkIcon className="h-5 w-5"/></button></div><label className="mt-5 flex cursor-pointer flex-col items-center rounded-xl border-2 border-dashed border-slate-300 px-5 py-10 text-center hover:border-indigo-400"><ArrowUpTrayIcon className="h-9 w-9 text-indigo-500"/><b className="mt-3 text-sm">Drop your file here, or click to browse</b><span className="mt-1 text-xs text-slate-500">PDF, DOCX, TXT and other text files · Max 50 MB</span><input type="file" className="hidden" accept=".pdf,.doc,.docx,.txt" onChange={()=>{setUploading(false);setTimeout(()=>setUploading(true),50)}}/></label><button onClick={()=>setUploading(false)} className="mt-4 w-full rounded-lg bg-indigo-600 py-2.5 text-sm font-semibold text-white">Choose File</button></div></div>}
  </div>
}
