"""sessio table added

Revision ID: 4ce0bef99492
Revises: c7533356bb0f
Create Date: 2026-09-29 15:48:51.345526
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '4ce0bef99492'
down_revision: str | None = 'c7533356bb0f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
