"""sessio table updated

Revision ID: d597bb68ccc6
Revises: 4ce0bef99492
Create Date: 2026-09-29 15:54:33.439666
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd597bb68ccc6'
down_revision: str | None = '4ce0bef99492'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
